version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: docubrain-postgres
    network_mode: "host"
    environment:
      POSTGRES_USER: docubrain         # Set your PostgreSQL username
      POSTGRES_PASSWORD: docubrain@123 # Set your PostgreSQL password
      POSTGRES_DB: docubrain       # Default database created at startup
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose PostgreSQL on the host machine at port 5432
    restart: always
  web:
    build: .
    container_name: python-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=docubrain-postgres
      - DB_PORT=5432
      - DB_NAME=docubrain
      - DB_USER=docubrain
      - DB_PASSWORD=docubrain@123
    volumes:
      - .:/app

volumes:
  postgres_data:
    driver: local
