version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: docubrain-postgres
    environment:
      POSTGRES_USER: docubrain         # Set your PostgreSQL username
      POSTGRES_PASSWORD: docubrain@123 # Set your PostgreSQL password
      POSTGRES_DB: docubrain       # Default database created at startup
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose PostgreSQL on the host machine at port 5432
    restart: always

volumes:
  postgres_data:
    driver: local
