"""Create opd_record table

Revision ID: 7e5b7bd2ab35
Revises: 
Create Date: 2024-09-15 17:56:40.879362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5b7bd2ab35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opd_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('auth_file_path', sa.String(), nullable=True),
    sa.Column('value_ai', sa.String(), nullable=True),
    sa.Column('value_actual', sa.String(), nullable=True),
    sa.Column('authorized_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opd_record')
    # ### end Alembic commands ###
